services:
  weblate:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - weblate-data:/app/data
      - ./settings_custom.py:/app/data/settings_custom.py:r

volumes:
  weblate-data:
