import os
from weblate.settings_docker import AUTHENTICATION_BACKENDS

AUTHENTICATION_BACKENDS = AUTHENTICATION_BACKENDS + (
    'custom_backends.CustomOidcPkceAuth',
)

# Pull secrets safely from the environment
SOCIAL_AUTH_CUSTOM_OIDC_PKCE_KEY = os.environ.get('SOCIAL_AUTH_CUSTOM_OIDC_PKCE_KEY')
SOCIAL_AUTH_CUSTOM_OIDC_PKCE_SECRET = os.environ.get('SOCIAL_AUTH_CUSTOM_OIDC_PKCE_SECRET')
SOCIAL_AUTH_CUSTOM_OIDC_PKCE_OIDC_ENDPOINT = os.environ.get('SOCIAL_AUTH_CUSTOM_OIDC_PKCE_REALM')

